version: '2'
networks:
  srv:
  gitlab:

services:
  traefik:
    image: traefik:1.7.11
    command: >
     --api
     --api.statistics
    restart: always
    ports:
      - '80:80'
      - '443:443'
    expose:
      - '8080:8080'
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:traefik.${SITE}'
      - 'traefik.frontend.auth.basic.users=${USER}:${HASHED_PASSWORD}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik/traefik.toml:/traefik.toml'
      - './traefik/acme.json:/acme.json'
      - './traefik/logs:/logs'

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - 'elasticsearch'
    ports:
      - '24224:24224'
      - '24224:24224/udp'
    logging:
        driver: 'json-file'
        options:
            max-size: 100m
            max-file: '5'
    labels:
      - 'traefik.enable=false'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    environment:
      - 'cluster.name=docker-cluster'
      - 'bootstrap.memory_lock=true'
      - 'discovery.type=single-node'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    labels:
      - 'traefik.enable=false'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    links:
      - 'elasticsearch'
    ports:
      - '5601:5601'
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:kibana.${SITE}'
      - 'traefik.port=5601'
      - 'traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}'

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.${SITE}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${SITE}:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '2224:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:gitlab.${SITE}'
      - 'traefik.port=80'

  runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - './gitlab/runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - gitlab
    links:
      - gitlab
    labels:
      - 'traefik.enable=false'
    environment:
      - 'GITLAB_URL=https://gitlab${SITE}/'
      - 'GITLAB_TOKEN=_p9fW2gr4GiqAP6zrsaT'

  nginx:
    image: nginx:stable-alpine
    volumes:
      - './nginx:/etc/nginx/conf.d'
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=nginx'
      - 'traefik.frontend.rule=Host:${SITE}'
      - 'traefik.port=80'

  cyprine:
    image: nginx:stable-alpine
    volumes:
      - './cyprine:/etc/nginx/conf.d'
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:${SITE2}'
      - 'traefik.port=80'

  transmission:
    image: linuxserver/transmission:2.94-r1-ls12
    restart: always
    environment:
      - 'PGID=1000'
      - 'PUID=1000'
      - 'TZ=Europe/Paris'
    ports:
      - '51413:51413'
      - '51413:51413/udp'
    volumes:
      - './transmission/config:/config'
      - './transmission/downloads:/downloads'
      - './transmission/watch:/watch'
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:torrent.${SITE}'
      - 'traefik.port=9091'
      - 'traefik.frontend.auth.basic.users=${USERNAME}:${HASHED_PASSWORD}'

  vpn:
    image: hwdsl2/ipsec-vpn-server:latest
    restart: always
    privileged: true
    environment:
      - 'VPN_IPSEC_PSK='
      - 'VPN_USER='
      - 'VPN_PASSWORD='
      - 'VPN_ADDL_USERS=' # space separated values
      - 'VPN_ADDL_PASSWORDS=' # space separated values
    ports:
      - '500:500'
      - '4500:4500/udp'
    volumes:
      - '/lib/modules:/lib/modules:ro'

  jupyter:
    image: jupyter/base-notebook:2662627f26e0
    restart: always
    environment:
      - 'JUPYTER_ENABLE_LAB=yes'
    volumes:
      - './jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py'
      - './jupyter/notbooks:/notebooks'
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:jupyter.${SITE}'
      - 'traefik.port=8888'

  pastebin:
    image: mkodockx/docker-pastebin:latest
    restart: always
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:paste.${SITE}'
      - 'traefik.port=80'

  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - './nextcloud/db:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=pass'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=nextcloud'
    labels:
      - 'traefik.enable=false'

  nextcloud:
    image: nextcloud
    restart: always
    links:
      - nextcloud-db
    volumes:
      - './nextcloud/data:/var/www/html'
    networks:
      - srv
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:cloud.${SITE}'
      - 'traefik.port=80'

  # weechat:
  #   image: craighurley/docker-weechat:latest
  #   restart: always
  #   volumes:
  #     - './weechat:/home/user/.weechat'
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.frontend.rule=Host:irc.${SITE}'
  #     - 'traefik.port=80'

  # doc:
  #   image: jekyll/jekyll:latest
  #   command: jekyll serve --force_polling --livereload
  #   # restart: always
  #   environment:
  #     - 'JEKYLL_ENV=docker'
  #   volumes:
  #     - './documentation/site:/srv/jekyll'
  #     - './documentation/bundle:/usr/local/bundle'
  #   networks:
  #     - srv
  #   labels:
  #     - 'traefik.enable=true'
  #     - 'traefik.frontend.rule=Host:wiki.${SITE}'
  #     - 'traefik.port=4000'