version: '2'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    user: nobody
    environment:
      - ROCKET_PORT=8080
      - ADMIN_TOKEN=${USERS}
    volumes:
      - ./bitwarden/data:/data
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bitwarden.rule=Host(`bitwarden.${SITE:-localhost}`)'
      - 'traefik.http.services.bitwarden.loadbalancer.server.port=8080'
