version: '2'

networks:
  hits-internal:

services:
  hits:
    image: tommoulard/hits
    networks:
      - 'srv'
      - 'hits-internal'
    restart: always
    depends_on:
      - 'hits-postgresql'
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:4000']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.hits.rule=Host(`hits.${SITE:-localhost}`)'
      - 'traefik.http.services.hits.loadbalancer.server.port=4000'

  hits-postgresql:
    image: postgres
    restart: always
    user: 1000:1000
    networks:
      hits-internal:
        aliases:
          - 'postgresql'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - './hits/postgresql/:/var/lib/postgresql/data'

