version: '2'

services:
  pastebin:
    image: mkodockx/docker-pastebin:latest
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pastebin.rule=Host(`pastebin.${SITE:-localhost}`)'
      - 'traefik.http.services.pastebin.loadbalancer.server.port=80'
