version: '2'

services:
  theia:
    image: theiaide/theia
    volumes:
      - '${HOME}:/home/project:cached'
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.theia.rule=Host(`theia.${SITE}`)'
      - 'traefik.http.services.theia.loadbalancer.server.port=3000'
      - 'traefik.http.routers.theia.middlewares=basic_auth@docker'
