version: '2'

services:
  arachni:
    image: arachni/arachni
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:arachni.${SITE}'
      - 'traefik.port=9292'
