concurrent = 10
check_interval = 1
log_level = "info"
log_format = "json"

[session_server]
  session_timeout = 1800

[[runners]]
  token = ""
  name = "The Best Runner"
  url = "http://gitlab/"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "ubuntu:19.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    run_exec = ""
