version: '2'

services:
  traefik:
    image: traefik:1.7.12
    command: >
     --api
     --api.statistics
     --ping=true
    ports:
      - '80:80'
      - '443:443'
    networks:
      - 'srv'
    restart: always
    healthcheck:
      test: ['CMD', './traefik', 'healthcheck']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:traefik.${SITE}'
      - 'traefik.frontend.auth.basic.users=${USERS}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './traefik/traefik.toml:/traefik.toml'
      - './traefik/logs:/logs'
