logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[traefikLog]
  filePath = "/logs/traefik.log"
  format   = "json"
[accessLog]
  filePath = "/logs/access.log"
  format = "json"
  bufferingSize = 100
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.headers]
      defaultMode = "keep"

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

# API definition
[api]
entryPoint = "traefik"
dashboard = true
  [api.statistics]
    recentErrors = 42

[acme]
email = "tom@moulard.org"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
acmelogging = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
watch = true
exposedByDefault = false
network = "srv"

