defaultEntryPoints = ["http", "https"]

[traefikLog]
  filePath = "/logs/traefik.log"
  format   = "json"
[accessLog]
  filePath = "/logs/access.log"
  format = "json"
  bufferingSize = 100
  [accessLog.fields]
    defaultMode = "keep"
    [accessLog.fields.headers]
      defaultMode = "keep"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    compress = true
      [entryPoints.https.tls]

# API definition
[api]
entryPoint = "traefik"
dashboard = true
  [api.statistics]
    recentErrors = 42
