version: '2'

services:
  nextcloud:
    image: nextcloud
    links:
      - nextcloud-db
    volumes:
      - './nextcloud/data:/var/www/html'
    networks:
      - 'srv'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:80']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nextcloud.rule=Host(`nextcloud.${SITE:-localhost}`)'
      - 'traefik.http.services.nextcloud.loadbalancer.server.port=80'

      # https://docs.nextcloud.com/server/22/admin_manual/installation/harden_server.html
      - 'traefik.http.middlewares.header-nextcloud.headers.stsincludesubdomains=true'
      - 'traefik.http.middlewares.header-nextcloud.headers.stspreload=true'
      - 'traefik.http.middlewares.header-nextcloud.headers.stsseconds=15552000'
      - 'traefik.http.middlewares.header-nextcloud.headers.customFrameOptionsValue=SAMEORIGIN'
      - 'traefik.http.middlewares.header-nextcloud.headers.browserXssFilter=true'
      - 'traefik.http.middlewares.header-nextcloud.headers.contentTypeNosniff=true'
      - 'traefik.http.middlewares.header-nextcloud.headers.referrerPolicy=no-referrer'
      - 'traefik.http.routers.nextcloud.middlewares=header-nextcloud'

  nextcloud-db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - './nextcloud/db:/var/lib/mysql'
    environment:
      - 'MYSQL_ROOT_PASSWORD=pass'
      - 'MYSQL_PASSWORD='
      - 'MYSQL_DATABASE=nextcloud'
      - 'MYSQL_USER=nextcloud'
    restart: always
    healthcheck:
      test: ['CMD', 'mysqlcheck', '--all-databases', '-ppass']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=false'
