version: '2'

services:
  jackett:
    image: linuxserver/jackett:v0.15.5-ls61
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    networks:
      - 'srv'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:jackett.${SITE}'
      - 'traefik.port=9117'
      - 'traefik.frontend.auth.basic.users=${USERS}'
