version: '2'

services:
  jackett:
    image: linuxserver/jackett:v0.15.5-ls61
    environment:
      - PUID=1000
      - PGID=1000
      - 'TZ=${TZ}'
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    networks:
      - 'srv'
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '0.0.0.0:9117/UI/Login?ReturnUrl=%2FUI%2FDashboard']
      interval: 10s
      timeout: 10s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jackett.rule=Host(`jackett.${SITE}`)'
      - 'traefik.http.services.jackett.loadbalancer.server.port=9117'
      - 'traefik.http.routers.jackett.middlewares=basic_auth@docker'
