name: Docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./test.sh
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: log.log
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: config.yml