name: Docker

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: ./test.sh
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: |
            log.log
            test_patch.patch
